/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-02-04 08:33:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import article.DBManager;
import java.sql.SQLException;

public final class singlepost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */\r\n");
      out.write("    .row.content {height: 1500px}\r\n");
      out.write("    \r\n");
      out.write("    /* Set gray background color and 100% height */\r\n");
      out.write("    .sidenav {\r\n");
      out.write("      background-color: #f1f1f1;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* Set black background color, white text and some padding */\r\n");
      out.write("    footer {\r\n");
      out.write("      background-color: #555;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* On small screens, set height to 'auto' for sidenav and grid */\r\n");
      out.write("    @media screen and (max-width: 767px) {\r\n");
      out.write("      .sidenav {\r\n");
      out.write("        height: auto;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .row.content {height: auto;} \r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"SinglePost\" method=\"post\">\r\n");
try {
	DBManager inst = DBManager.getInstance();
	Connection con=inst.getConnection();
	HttpSession s=request.getSession();
	
	String sql = "select * from article where articleID="+s.getAttribute("id");
	Statement stm= con.createStatement();
	ResultSet rs = stm.executeQuery(sql);
	
	
	while (rs.next()){

      out.write("\r\n");
      out.write("    <div class=\"col-sm-9\">\r\n");
      out.write("   <hr>\r\n");
      out.write("      <h2>");
      out.print(rs.getString("articleTitel"));
      out.write("</h2>\r\n");
      out.write("      <h5><span class=\"glyphicon glyphicon-time\"></span>");
      out.print(rs.getString("date"));
      out.write("</h5>\r\n");
      out.write("      <p>");
      out.print(rs.getString("article"));
      out.write("</p>\r\n");
      out.write("      <br><br>\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write(" ");

}
}catch(Exception e)
{
	e.printStackTrace();
}

      out.write(" \r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("        <div class=\"col-sm-10\">\r\n");
      out.write("        <h2>Comments:</h2>\r\n");

	HttpSession s=request.getSession();
	DBManager inst = DBManager.getInstance();
	Connection con=inst.getConnection();
	PreparedStatement pst=null;
	String sa = "WITH RECURSIVE c AS ("	
			+"SELECT cID, content, undercomment, articleID, 1 as level, convert ( cID, CHAR) as ORDERSTR from comment"
			+"where undercomment is null AND articleID="+s.getAttribute("id")+""
			+"union all"
			+"select a.cID, a.content, a.undercomment, a.articleID, b.level+1 as level, CONCAT(b.ORDERSTR,'->',a.cID) as ORDERSTR"
			+"from comment a join c as b on (a.undercomment = b.cID)"
			+")"
			+"SELECT * FROM c ORDER BY ORDERSTR";
	
	Statement stm= con.createStatement();
	ResultSet rs = stm.executeQuery(sa);
	
	
	while (rs.next()){

      out.write("\r\n");
      out.write("          <h4>Anja <small>Sep 29, 2015, 9:12 PM</small></h4>\r\n");
      out.write("          <p>");
      out.print(rs.getString("content"));
      out.write("</p>\r\n");
      out.write("          <br>\r\n");
      out.write("        ");

        }
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
